service: docker

language: bash

# notifications:
#   email:
#       - funa@hiroshima-cu.ac.jp

addons:
    apt:
        packages:
            - curl

before_install:
    - docker run --name latex -itd -v $PWD:/workdir johejo/debian-latex-jp:latest

script:
    - docker exec latex bash -c "make clean"
    - docker exec latex bash -c "make all"

deploy:
    - provider: script
    - script: deploy.sh