# service:
#     - docker

addons:
    apt:
        packages:
            - texlive
            - texlive-lang-japanese


# before_install:
    # - docker pull paperist/alpine-texlive-ja
    # - docker run --rm -itd -v $PWD:/workdir paperist/alpine-texlive-ja


script:
    - make clean
    - make all
