# service:
#     - docker

addons:
    apt:
        packages:
            - curl
            - texlive-full


# before_install:
    # - docker pull paperist/alpine-texlive-ja
    # - docker run --rm -itd -v $PWD:/workdir paperist/alpine-texlive-ja


script:
    - make clean
    - make all

deploy:
    - curl -X POST -H "Authorization: Bearer $DROPBOX_TOKEN" -T prologue.pdf https://content.dropboxapi.com/1/files_put/auto/prologue.pdf
