service: docker

language: bash

notifications:
  email:
    - funa@hiroshima-cu.ac.jp
  on_success: always
  on_failure: never

addons:
  apt:
    packages:
      - curl

before_install:
    - docker run --name latex -itd -v $PWD:/workdir johejo/debian-latex-jp:latest

script:
    - docker exec latex bash build.sh
    - ./upload.sh
